name: Webpack & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Add .nojekyll file
      run: touch dist/.nojekyll

    - name: Deploy to branch
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: deploy
        folder: dist
