name: Webpack & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Archive build output
      run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn
      
    - name: Deploy to GitHub Pages w/ beta action
      uses: actions/deploy-pages@v1-beta
